const instructions = document.getElementById('instructions');
/**
 * Hide the instructions modal on page loading, if a user has already read them.
 */
const hideInstructions = () => {
  if (localStorage.getItem('instructions') === 'read') {
    instructions.style.display = 'none';
  }
};
window.onload = hideInstructions;
/**
 * Close the instructions modal on a user input.
 */
const closeInstructions = () => {
  instructions.style.opacity = '0';
  instructions.style.visibility = 'hidden';
  /**
   * Remember that a user has already read the instructions.
   */
  if (typeof(Storage) !== 'undefined') {
    localStorage.setItem('instructions', 'read');
  }
};
const closeInstructionsButton = document.getElementById('close-instructions');
closeInstructionsButton.addEventListener('click', closeInstructions, false);
/**
 *
 */
const gameWinner = () => {

};

const playFeedback = document.getElementById('play-feedback');
/**
 *
 * @param {string} playerChoice - One of ‘rock’, ‘paper’, or ‘scissors’ chosen by the player.
 * @param {string} computerChoice - One of ‘rock’, ‘paper’, or ‘scissors’ randomly generated by the computer.
 */
const gamePlay = (playerChoice, computerChoice) => {
  const playerLose = `You lose, <strong>${computerChoice}</strong> beats <strong>${playerChoice}</strong>.`;
  const playerWon = `You won, <strong>${playerChoice}</strong> beats <strong>${computerChoice}</strong>.`;
  if (playerChoice === computerChoice) {
    playFeedback.innerHTML = `Tie. You and the computer both chose <strong>${playerChoice || computerChoice}</strong>.`;
    return;
  } else {
    if (playerChoice === 'rock') {
      if (computerChoice === 'paper') {
        playFeedback.innerHTML = playerLose;

      } else {
        playFeedback.innerHTML = playerWon;

      }
    } else if (playerChoice === 'paper') {
      if (computerChoice === 'rock') {
        playFeedback.innerHTML = playerWon;

      } else {
        playFeedback.innerHTML = playerLose;

      }
    } else {
      if (computerChoice === 'rock') {
        playFeedback.innerHTML = playerLose;

      } else {
        playFeedback.innerHTML = playerWon;

      }
    }
  }
  gameWinner();
};
/**
 * Generate a random string between ‘rock’, ‘paper’, and ‘scissors’.
 */
const computerPlay = () => {
  const computerChoices = ['rock', 'paper', 'scissors'];
  return computerChoices[Math.floor(Math.random() * computerChoices.length)];
};
/**
 * Get the user choice between ‘rock’, ‘paper’, and ‘scissors’ from the clicked button and start a new game.
 */
const playerPlay = playerChoice => {
  gamePlay(playerChoice, computerPlay());
};
const playerChoices = document.querySelectorAll('#player button');
playerChoices.forEach(playerChoice => {
  playerChoice.addEventListener('click', event => {
    playerPlay(playerChoice.id);
  }, false);
});